version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/usr/src/my-app/app
    ports:
      - "4000:4000"
    # env_file:
    #   - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=4000
    depends_on:
      - redis
  redis:
    image: "redis:alpine"