name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and test with Docker Compose
        run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit