name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Node.js setup
        with:
          node-version: "18"
      - name: Install npm dependencies
        run: npm ci
      -name: install and run redis-server
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server
          redis-server --daemonize yes --requirepass test_env --port 6380
      - name: Run tests
        run: npm run test
      
      - name: test build
        run: npm run build