name: testAndDeploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2

permissions:
  id-token: write # This is required for reading the JWT
  contents: read # This is required for reading the repository files

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and test with Docker Compose
        run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::766838695223:role/github_bayy1216_express_OIDC
          role-seesion-name: sampleSessionName
          aws-region: ${{ env.AWS_REGION }}